### ISSUE TITLE
Cache is not working

### ISSUE THREAD

**Issue by aneesh1122** [Maloy-Android/MuzzaRework#2]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1) set a cache limit
2) play any song 
3) go back to settings -> storage
4) the cache size is still 0MB

### Expected behavior

Cache size should increase

### Actual behavior

Cache is not saved

### Logs

NA

### OuterTune version

Muzza latest patch from telegram group

### Android version

Android 13 HyperOS

**Comment by Maloy-Android** [comment]
Done https://github.com/Maloy-Android/MuzzaRework/commit/1e54286ec3c8941405085e78373f54350101f58e
